services:
  - type: web
    name: tnadlink
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon  # Choose a region closest to Tennessee
    plan: standard  # Choose appropriate plan based on needs
    healthCheckPath: /www/delivery/lg.php
    domains:
      - tnadlink.com
      - www.tnadlink.com
    envVars:
      - key: SITE_URL
        value: https://tnadlink.com
      - key: SITE_NAME
        value: TN Ad Link
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_PORT
        value: 5432
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_DB_NAME
        sync: false
      - key: SUPABASE_DB_SCHEMA
        value: tnadlink
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
